name: Encrypt Contributor Info

on:
  push:
    branches:
      - main

jobs:
  encrypt-contributor-info:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install git filter-repo
      run: |
        sudo apt-get update
        sudo apt-get install -y git-filter-repo

    - name: Install dependencies
      run: npm install crypto

    - name: Get original email addresses
      id: get-original-email
      run: |
        ORIGINAL_EMAILS=$(git log --format='%ae' | sort -u | paste -s -d, -)
        echo "::set-output name=original-emails::$ORIGINAL_EMAILS"

    - name: Git history rewrite
      run: |
        git filter-repo --email-callback '
          if email in ENV["ORIGINAL_EMAILS"].split(","):
              return (ENV["GITHUB_ACTOR"] + "@nobody.com", "Name")
          return (email, "Name")
        '

    - name: Push changes
      run: |
        git push origin main --force

      env:
        ORIGINAL_EMAILS: ${{ steps.get-original-email.outputs.original-emails }}
