name: Encrypt Commit Data

on:
  # 死循环了
  # push:
  #   branches:
  #     - '*'
  workflow_dispatch:

jobs:
  encrypt-commits:
    runs-on: ubuntu-latest
    env:
      # 仓库的SSH地址
      REPOSITORY_URL: git@github.com:xiwangly2/action-test111.git
      # 邮件字符串
      RANDOM_STRING: $(openssl rand -hex 10)@nobody.com
      # RANDOM_STRING: noreply@github.com
      # 用户名
      USER_NAME: Anonymous
      # USER_NAME: github-actions[bot]
    steps:
    - name: Clone repository and set up SSH key && Encrypt commit data
      run: |
        mkdir -p ~/.ssh
        # SSH私钥 使用ed25519
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        # SSH公钥
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_ed25519.pub
        chmod 600 ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519.pub
        # 启动ssh-agent并添加私钥的密码短句
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_ed25519 <<<"${{ secrets.SSH_PASSPHRASE }}"
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git clone ${{ env.REPOSITORY_URL }} a_repository
        cd a_repository
        git filter-branch --env-filter "
        if [ \"\$GIT_COMMITTER_EMAIL\" != '${{ env.RANDOM_STRING }}' ]
        then
            export GIT_COMMITTER_NAME='${{ env.USER_NAME }}'
            export GIT_COMMITTER_EMAIL='${{ env.RANDOM_STRING }}'
        fi
        " --tag-name-filter cat -- --branches --tags

        # 使用SSH密钥进行推送
        git push --force --tags origin 'refs/heads/*'
