name: Encrypt Commit Data

on:
  push:
    branches:
      - '*'

jobs:
  encrypt-commits:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate random string
      id: random-string
      run: echo "::set-output name=random_string::$(openssl rand -hex 10)"

    - name: Encrypt commit data
      run: |
        RANDOM_STRING=${{ steps.random-string.outputs.random_string }}
        git filter-branch --env-filter "
          export GIT_COMMITTER_NAME='Anonymous'
          export GIT_COMMITTER_EMAIL='${RANDOM_STRING}@example.com'
          export GIT_AUTHOR_NAME='Anonymous'
          export GIT_AUTHOR_EMAIL='${RANDOM_STRING}@example.com'
        " --tag-name-filter cat -- --branches --tags

        git push --force --tags origin 'refs/heads/*'
      env:
        RANDOM_STRING: ${{ steps.random-string.outputs.random_string }}
