name: Encrypt Commit Data

on:
  push:
    branches:
      - '*'

jobs:
  encrypt-commits:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Encrypt commit data
      run: |
        RANDOM_STRING=$(openssl rand -hex 10)
        git filter-branch --env-filter "
          if [ \"\$GIT_COMMITTER_EMAIL\" != \"xxx@nobody.com\" ]
          then
              export GIT_COMMITTER_NAME='Anonymous'
              export GIT_COMMITTER_EMAIL='${RANDOM_STRING}@nobody.com'
          fi
          if [ \"\$GIT_AUTHOR_EMAIL\" != \"xxx@nobody.com\" ]
          then
              export GIT_AUTHOR_NAME='Anonymous'
              export GIT_AUTHOR_EMAIL='${RANDOM_STRING}@nobody.com'
          fi
        " --tag-name-filter cat -- --branches --tags

        # 使用GitHub Actions的SSH密钥进行推送
        git push --force --tags origin 'refs/heads/*'
      env:
        GIT_SSH_COMMAND: ${{ secrets.GIT_SSH_COMMAND }}
