name: Encrypt Contributor Info

on:
  push:
    branches:
      - main
    # 仅在非 github-actions[bot] 用户的推送时触发
    paths-ignore:
      - '**/.github/workflows/**'

jobs:
  encrypt-contributor-info:
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install crypto

    - name: Get original email addresses
      run: |
        ORIGINAL_EMAILS=$(git log --format='%ae' | sort -u | paste -s -d, -)
        echo "Original email addresses: $ORIGINAL_EMAILS"
        echo "New username: ${{ github.actor }}"
        echo "New email address: ${{ github.actor }}@nobody.com"

    - name: Git history rewrite
      run: |
        git filter-branch --env-filter '
          OLD_EMAILS="$ORIGINAL_EMAILS"
          CORRECT_NAME="${{ github.actor }}"
          CORRECT_EMAIL="${{ github.actor }}@nobody.com"

          if [[ "$OLD_EMAILS" == *"$GIT_COMMITTER_EMAIL"* ]]
          then
              export GIT_COMMITTER_NAME="$CORRECT_NAME"
              export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
          fi
          if [[ "$OLD_EMAILS" == *"$GIT_AUTHOR_EMAIL"* ]]
          then
              export GIT_AUTHOR_NAME="$CORRECT_NAME"
              export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
          fi
        ' --tag-name-filter cat -- --branches --tags

        git push origin main --force

      env:
        ORIGINAL_EMAILS: ${{ steps.get-original-email.outputs.original-emails }}
